In [1]:
# Install TensorFlow using pip
!pip install tensorflow

  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
  Using cached charset_normalizer-3.4.4-cp313-cp313-win_amd64.whl.metadata (38 kB)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
  Using cached markupsafe-3.0.3-cp313-cp313-win_amd64.whl.metadata (2.8 kB)
   ---------------------------------------- 0.0/332.0 MB ? eta -:--:--
   - -------------------------------------- 10.7/332.0 MB 57.5 MB/s eta 0:00:06
   --- ------------------------------------ 25.7/332.0 MB 62.3 MB/s eta 0:00:05
   ---- ----------------------------------- 41.4/332.0 MB 67.0 MB/s eta 0:00:05
   ------ --------------------------------- 55.6/332.0 MB 67.3 MB/s eta 0:00:05
   -------- ------------------------------- 70.3/332.0 MB 67.9 MB/s eta 0:00:04
   ---------- ----------------------------- 84.4/332.0 MB 68.1 MB/s eta 0:00:04
   ----------- ---------------------------- 98.3/332.0 MB 68.0 MB/s eta 0:00:04
   ------


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Users\clauds\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip


#import numpy package

In [2]:
import numpy as np

In [ ]:
#Task 1: Create Two Sample TensorsWe will create high-dimensional arrays (tensors). Deep learning models often work with 3D or 4D tensors (e.g., a batch of color images is 4D: Batch Size $\times$ Height $\times$ Width $\times$ Color Channels).Explanation:We will use np.random.randint to generate random integers. This is often better for learning than np.zeros or np.ones because it makes it easier to track how data moves during reshaping or slicing.

In [2]:
# Create two 3-D tensors of shape (2, 3, 4)
# Think of this as: 2 matrices, each having 3 rows and 4 columns
tensor_a = np.random.randint(low=0, high=10, size=(2, 3, 4))
tensor_b = np.random.randint(low=0, high=10, size=(2, 3, 4))

print("Tensor A:\n", tensor_a)
print("\nShape of Tensor A:", tensor_a.shape)

Tensor A:
 [[[5 4 3 8]
  [9 9 3 0]
  [3 1 3 6]]

 [[0 8 8 9]
  [0 3 4 5]
  [3 5 6 7]]]

Shape of Tensor A: (2, 3, 4)


In [ ]:
#Task 2: Element-wise AdditionExplanation:Element-wise operations apply a mathematical operation between corresponding elements in two tensors. For this to work without "broadcasting" (an advanced topic), the two tensors usually need to have the exact same shape.Mathematically, if $C = A + B$, then for every specific position $(i, j, k)$, $C_{ijk} = A_{ijk} + B_{ijk}$.

In [3]:
# Adding two tensors of the exact same shape
tensor_sum = tensor_a + tensor_b

print("Sum:\n", tensor_sum)

Sum:
 [[[ 5  5 10 13]
  [16 15  6  8]
  [ 7  4 12 10]]

 [[ 4 10 14 10]
  [ 9  4 11 12]
  [11  8 11  7]]]


In [ ]:
#Task 3: Element-wise MultiplicationExplanation:This is often called the Hadamard Product. It is not the same as Matrix Multiplication (Dot Product).In element-wise multiplication, we simply multiply the number at position [0,0,0] in Tensor A by the number at [0,0,0] in Tensor B.Symbol: Often denoted by $\odot$ or simply $*$ in code.Use case: Used frequently in neural networks for things like masking (hiding certain parts of an image) or activation functions

In [4]:
# Element-wise multiplication
tensor_mult = tensor_a * tensor_b

print("Element-wise Product:\n", tensor_mult)

Element-wise Product:
 [[[ 0  4 21 40]
  [63 54  9  0]
  [12  3 27 24]]

 [[ 0 16 48  9]
  [ 0  3 28 35]
  [24 15 30  0]]]


In [ ]:
#Task 4: Reshape a TensorExplanation:Reshaping is critical in Deep Learning. You might need to flatten an image (2D) into a vector (1D) to feed it into a standard neural network layer.The Golden Rule of Reshaping: The total number of elements must remain the same.Our tensor_a has shape $(2, 3, 4)$.Total elements: $2 \times 3 \times 4 = 24$.We can reshape this into any shape that multiplies to 24, such as $(6, 4)$, $(24,)$, or $(1, 24)$.

In [5]:
# Reshaping the (2, 3, 4) tensor into a 2D matrix of shape (6, 4)
reshaped_tensor = tensor_a.reshape(6, 4)

print("Original Shape:", tensor_a.shape)
print("New Shape:", reshaped_tensor.shape)
print("\nReshaped Tensor:\n", reshaped_tensor)

Original Shape: (2, 3, 4)
New Shape: (6, 4)

Reshaped Tensor:
 [[5 4 3 8]
 [9 9 3 0]
 [3 1 3 6]
 [0 8 8 9]
 [0 3 4 5]
 [3 5 6 7]]


In [ ]:
#Task 5: Slicing and Indexing
#Explanation: Slicing allows you to extract specific sub-sections of your tensor. The syntax follows [start:stop:step].

#: selects everything in that dimension.

#0:2 selects indices 0 up to (but not including) 2.

#Since our tensor is 3D (Block, Row, Column), we need three indices to access a specific number, or ranges to access a chunk.

In [6]:
# Select the first block, first 2 rows, and all columns
# Syntax: tensor[dimension_1, dimension_2, dimension_3]
slice_example = tensor_a[0, 0:2, :]

print("Original Shape:", tensor_a.shape)
print("Sliced Shape:", slice_example.shape)
print("\nSliced Data:\n", slice_example)

Original Shape: (2, 3, 4)
Sliced Shape: (2, 4)

Sliced Data:
 [[5 4 3 8]
 [9 9 3 0]]


In [ ]:
#Task 6: Combining Tensors
#Explanation: In Neural Networks, you often need to merge data. For example, merging two different features of a dataset.

#Concatenation: Joins tensors along an existing axis. The dimension of that axis increases.

#Stacking: Joins tensors along a new axis. The rank (number of dimensions) increases.

#We will use np.concatenate here. If we concatenate along axis=0, we are adding more "blocks" to our pile

In [7]:
# Concatenating along axis 0 (stacking them on top of each other vertically)
# (2,3,4) + (2,3,4) -> (4,3,4)
combined_tensor = np.concatenate((tensor_a, tensor_b), axis=0)

print("Shape after concatenation:", combined_tensor.shape)

Shape after concatenation: (4, 3, 4)


In [ ]:
#Task 7: Splitting Tensors
Explanation: This is the inverse of concatenation. You might use this to split a dataset into "Training" and "Testing" sets. np.array_split allows us to divide the tensor into equal (or near-equal) chunks

In [ ]:
# Split the large combined tensor into 2 equal parts
# We combined them earlier, now we split them back
split_tensors = np.array_split(combined_tensor, 2, axis=0)

print("Shape of first split:", split_tensors[0].shape)
print("Shape of second split:", split_tensors[1].shape)

In [ ]:
#Task 8: Basic Mathematical Operations
#Explanation: These are "Aggregation" functions. They take a tensor and reduce it to a smaller shape (or a single number) by summarizing the data.

#sum(): Adds everything up.

#mean(): The average.

#std(): Standard Deviation (how spread out the numbers are).

#You can apply these to the whole tensor, or just along a specific axis (e.g., "give me the average of every row").

In [ ]:
# Global aggregation (reduces to a single number)
total_sum = np.sum(tensor_a)
mean_val = np.mean(tensor_a)

# Aggregation along an axis (reduces dimensions)
# Summing along axis 0 collapses the two "blocks" together
sum_axis_0 = np.sum(tensor_a, axis=0)

print(f"Total Sum: {total_sum}")
print(f"Mean Value: {mean_val}")
print(f"Sum along Axis 0 shape: {sum_axis_0.shape}") # Should be (3, 4)

In [ ]:
##TASK 2

In [ ]:
#We will use Keras, which is the high-level API built into TensorFlow. Keras makes deep learning accessible by abstracting away the complex mathematics of tensor calculus, allowing you to focus on the architecture.

In [17]:
import tensorflow as tf
from tensorflow.keras import layers, models

In [ ]:
#Step 1: Define a Simple Neural Network Model
#In-Depth Explanation: We will use the Sequential API. Imagine this as a linear stack of pancakes. You place one layer on top of another. Data flows from the input (top), through each layer, to the output (bottom).

#We are building a Multi-Layer Perceptron (MLP).

#Input Layer: The entry point for data. We must tell the model what shape the data has (e.g., a vector of length 10).

#Hidden Layers: The "thinking" layers. We use Dense layers, which means every neuron in this layer is connected to every neuron in the previous layer.

#Activation Function: This is the "spark." Without it, a neural network is just linear algebra (like a big regression line). The activation function (like ReLU) introduces non-linearity, allowing the model to learn complex, curvy patterns.

#Output Layer: The final result. For a binary classification (Yes/No), we usually use 1 neuron.


In [18]:
# Initialize the container (the empty stack)
model = models.Sequential()

# 1. Add the first hidden layer
# - units=16: This layer has 16 neurons ("thinking units").
# - activation='relu': Rectified Linear Unit. It turns negative values to 0. 
# - input_shape=(8,): We expect an input vector with 8 features.
model.add(layers.Dense(units=16, activation='relu', input_shape=(8,)))

# 2. Add a second hidden layer
# We don't need input_shape here; Keras infers it from the previous layer.
model.add(layers.Dense(units=8, activation='relu'))

# 3. Add the output layer
# - units=1: A single number output (e.g., probability of "True")
# - activation='sigmoid': Squashes the output between 0 and 1.
model.add(layers.Dense(units=1, activation='sigmoid'))

In [ ]:
README for Step 1Sequential: Creates a linear stack of layers.Dense: A fully connected layer.Units: The number of neurons (nodes) in that layer. More units = more capacity to learn, but higher computational cost.ReLU: The standard activation function for hidden layers ($f(x) = max(0, x)$). It helps prevent the "vanishing gradient" problem.Sigmoid: Used for binary output. It forces the result to be a probability between 0 and 1.

In [ ]:
#Step 2: Compile the Model
#In-Depth Explanation: Defining the architecture (Step 1) is like building a car. Compiling is like connecting the engine, filling the gas tank, and installing the GPS. You are configuring how the model will learn.

#You must specify three things:

#Optimizer: The mechanic. It updates the weights based on the data to reduce error. Adam is the industry standard (it's adaptive and fast).

#Loss Function: The GPS. It calculates how far off the model's predictions are from the actual answers.

#Use binary_crossentropy for Yes/No tasks.

#Use categorical_crossentropy for Multi-class tasks.

#Use mean_squared_error for Regression (predicting prices, temp).

#Metrics: The dashboard. These are numbers for us (humans) to read, like "Accuracy". The model doesn't use this for learning, just for reporting.

In [20]:
# Compiling the model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [ ]:
README for Step 2

Optimizer ('adam'): A gradient descent algorithm that adjusts the learning rate automatically. It is generally the best "default" choice.

Loss ('binary_crossentropy'): The math formula that quantifies "error" for binary classification tasks. The goal of training is to minimize this number.

Metrics ('accuracy'): The percentage of correct predictions. Easier for humans to understand than the raw loss value.

In [ ]:
Step 3: Print Model SummaryIn-Depth Explanation:The summary() method is a crucial debugging tool. It prints a table showing the structure of your network.Key things to look for:Output Shape: It will look like (None, 16). The None represents the Batch Size. The model doesn't care if you feed it 1 example or 100 examples at once; it's flexible. The 16 is the number of neurons in that layer.Param # (Parameters): This is the total number of "knobs" the model can turn to learn patterns.Calculation: For a Dense layer, parameters = $(Inputs \times Neurons) + Bias$.Example for our first layer: 8 inputs $\times$ 16 neurons + 16 biases = $128 + 16 = 144$ parameters.

In [21]:
# View the architecture and parameter count
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 16)                  │             144 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 8)                   │             136 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │               9 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 289 (1.13 KB)

 Trainable params: 289 (1.13 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
README for Step 3

Output Shape: Shows the dimensions of data coming out of each layer. The first dimension is None (variable batch size).

Param #: The count of weights and biases (learnable variables).

Total Params: The complexity of your model. A simple model like this has hundreds; GPT-4 has over a trillion.

Trainable Params: The parameters that will actually be updated by the Optimizer during training.

In [ ]:
###PART 3

In [ ]:
Part A: The MNIST Handwritten Digit Classification.

In [ ]:
Part A: MNIST (Image Classification)
The MNIST dataset contains 70,000 small (28x28 pixel) grayscale images of handwritten digits (0-9). It is the "Hello World" of Computer Vision.

Step 1: Load and Preprocess the Dataset
Explanation:

Loading: Keras has MNIST built-in. It returns two tuples: one for training (learning) and one for testing (final exam).

Normalization: Pixel values range from 0 (black) to 255 (white). Neural networks converge much faster when inputs are small numbers (between 0 and 1). We divide by 255.0 to achieve this.

In [ ]:
README Step 1:

Normalization: Scaling data to the [0, 1] range. Crucial for stable training.

Shape: We have 60,000 images, each 28x28 pixels.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers, models, datasets