In [4]:
import tensorflow as tf
import numpy as np

# What is a tensor

Tensors are multi-dimensional arrays with a uniform type (called a dtype). You can see all supported dtypes at tf.dtypes.

If you're familiar with NumPy, tensors are (kind of) like np.arrays.

All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.

# 1. Create two samples tensor

A scalar tensor (single value)

In [5]:
a_scalar_value = tf.constant(10)

a_scalar_value

<tf.Tensor: shape=(), dtype=int32, numpy=10>

A list of values tensor

In [6]:
a_list_of_values = tf.constant([2.0, 1.5, 3.5])

a_list_of_values

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2. , 1.5, 3.5], dtype=float32)>

# 2. Element-wise addition of tensors

In [7]:
a = tf.constant(10)
b = tf.constant(5)

print(tf.add(a, b))

tf.Tensor(15, shape=(), dtype=int32)


In [8]:
matrix_a = tf.constant([[1, 2], 
                         [2, 1]])

matrix_b = tf.constant([[0, 1],
                         [1, 0]])

print(tf.add(matrix_a, matrix_b))

tf.Tensor(
[[1 3]
 [3 1]], shape=(2, 2), dtype=int32)


Addition but different types

In [9]:
print(tf.add(matrix_a, b))

tf.Tensor(
[[6 7]
 [7 6]], shape=(2, 2), dtype=int32)


# 3. Element-wise multiplication of tensors

In [10]:
a = tf.constant(10)
b = tf.constant(5)

print(tf.multiply(a, b))

tf.Tensor(50, shape=(), dtype=int32)


In [11]:
matrix_a = tf.constant([[1, 2], 
                         [2, 1]])

matrix_b = tf.constant([[0, 1],
                         [1, 0]])

print(tf.multiply(matrix_a, matrix_b))

tf.Tensor(
[[0 2]
 [2 0]], shape=(2, 2), dtype=int32)


Multiply matrix with a scalar

In [12]:
print(tf.multiply(matrix_a, b))

tf.Tensor(
[[ 5 10]
 [10  5]], shape=(2, 2), dtype=int32)


Element-wise multiplication in TensorFlow is performed using two tensors with identical shapes. This is because the operation multiplies elements in corresponding positions in the two tensors.

In [13]:
matrix_a = tf.constant([[1, 2]])

matrix_b = tf.constant([[0, 1]])

print(tf.multiply(matrix_a, matrix_b))

tf.Tensor([[0 2]], shape=(1, 2), dtype=int32)


In [14]:
matrix_a = tf.constant([[1, 2]])

matrix_b = tf.constant([[0], [1]])

print(tf.multiply(matrix_a, matrix_b)) # element wise multiplication
print()
print(tf.matmul(matrix_a, matrix_b)) # this is dot product

tf.Tensor([[2]], shape=(1, 1), dtype=int32)


# 4. Reshape tensor

In [15]:
a_list_of_values = tf.constant([2.0, 1.5, 3.5])

print(a_list_of_values.shape)
print()
print(a_list_of_values.shape.as_list())

(3,)

[3]


In [16]:
matrix_a = tf.constant([[1, 2], 
                         [2, 1]])

print(matrix_a.shape)
print()
print(matrix_a.shape.as_list())
print()

reshaped_matrix_a = tf.reshape(matrix_a, [4])
print(reshaped_matrix_a)

tf.Tensor([1 2 2 1], shape=(4,), dtype=int32)


# 5. Slicing and indexing tensors

Tensors follow indexing rules as Numpy

In [17]:
a = tf.constant([4, 5, 10, 7, 8])

print(a.numpy())
print()
print(a[0])
print(a[1])
print(a[4])
print()

print(a[1:3])

[ 4  5 10  7  8]

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)

tf.Tensor([ 5 10], shape=(2,), dtype=int32)


In [18]:
matrix_a = tf.constant([[1, 2, 3], 
                        [4, 5, 6],
                        [7, 8, 9]])

print(matrix_a[1:2])
print()
print(matrix_a[0:3,1:2])

tf.Tensor([[4 5 6]], shape=(1, 3), dtype=int32)

tf.Tensor(
[[2]
 [5]
 [8]], shape=(3, 1), dtype=int32)


# 6. Combining tensors

In [19]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

print(tf.stack([a,b], axis=0))
print()
print(tf.stack([a,b], axis=1))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


# 7. Splitting tensor

In [20]:
a = tf.constant([1,2,3,4])

a1, a2 = tf.split(a, num_or_size_splits=2, axis=0)
print(a1)
print()
print(a2)

tf.Tensor([1 2], shape=(2,), dtype=int32)

tf.Tensor([3 4], shape=(2,), dtype=int32)


# 8. Basic mathematical operation on tensor

In [21]:
a = tf.constant([1., 2., 3., 4.])
b = tf.constant([1.5, 1.5, 1.5, 1.5])

print(tf.add(a, b))
print()
print(tf.multiply(a, b))
print()
print(tf.subtract(a,b))
print()
print(tf.divide(a, b))

tf.Tensor([2.5 3.5 4.5 5.5], shape=(4,), dtype=float32)

tf.Tensor([1.5 3.  4.5 6. ], shape=(4,), dtype=float32)

tf.Tensor([-0.5  0.5  1.5  2.5], shape=(4,), dtype=float32)

tf.Tensor([0.6666667 1.3333334 2.        2.6666667], shape=(4,), dtype=float32)


# PART 1


## Task 1: Create Two Sample Tensors

We will create high-dimensional arrays (tensors). Deep learning models often work with 3D or 4D tensors. For example, a batch of color images is 4D:

**Batch Size × Height × Width × Color Channels**

### Explanation:

We will use `np.random.randint` to generate random integers. This is often better for learning than `np.zeros` or `np.ones` because it makes it easier to track how data moves during reshaping or slicing.

In [ ]:
# Create two 3-D tensors of shape (2, 3, 4)
# Think of this as: 2 matrices, each having 3 rows and 4 columns
tensor_a = np.random.randint(low=0, high=10, size=(2, 3, 4))
tensor_b = np.random.randint(low=0, high=10, size=(2, 3, 4))

print("Tensor A:\n", tensor_a)
print("\nShape of Tensor A:", tensor_a.shape)